import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import './index.css'
import App from './App.tsx'

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <App />
  </StrictMode>,
)
import React from 'react'; import { useForm, Controller } from 'react-hook-form'; import { TextField, Button, Checkbox, FormControlLabel, MenuItem, Select, InputLabel, FormControl } from '@mui/material'; const MyForm = () => { const { control, handleSubmit, reset } = useForm(); const onSubmit = data => { console.log(data); }; return ( <form onSubmit={handleSubmit(onSubmit)}> {/* Policy Number */} <Controller name="policyNumber" control={control} defaultValue="" render={({ field }) => <TextField {...field} label="Policy Number" variant="outlined" />} /> {/* City */} <Controller name="city" control={control} defaultValue="" render={({ field }) => <TextField {...field} label="City" variant="outlined" />} /> {/* Insured */} <Controller name="insured" control={control} defaultValue="" render={({ field }) => <TextField {...field} label="Insured" variant="outlined" />} /> {/* State Dropdown */} <FormControl fullWidth> <InputLabel id="state-label">State</InputLabel> <Controller name="state" control={control} defaultValue="" render={({ field }) => ( <Select {...field} labelId="state-label" label="State"> <MenuItem value='NY'>New York</MenuItem> <MenuItem value='CA'>California</MenuItem> <MenuItem value='TX'>Texas</MenuItem> </Select> )} /> </FormControl> {/* Agent Dropdown */} <FormControl fullWidth> <InputLabel id="agent-label">Agent</InputLabel> <Controller name="agent" control={control} defaultValue="" render={({ field }) => ( <Select {...field} labelId="agent-label" label="Agent"> <MenuItem value='1'>Agent1</MenuItem> <MenuItem value='2'>Agent2</MenuItem> <MenuItem value='3'>Agent3</MenuItem> </Select> )} /> </FormControl> {/* HCN Option Dropdown */} <FormControl fullWidth> <InputLabel id="hcn-label">HCN Option</InputLabel> <Controller name="hcnOption" control={control} defaultValue="" render={({ field }) => ( <Select {...field} labelId="hcn-label" label="HCN Option"> <MenuItem value='1'>Option 1</MenuItem> <MenuItem value='2'>Option 2</MenuItem> </Select> )} /> </FormControl> {/* Checkboxes */} <FormControlLabel control={<Checkbox />} name="includeCancelled" control={control} defaultValue={false} label="Include Cancelled Policies" /> <FormControlLabel control={<Checkbox />} name="includeExpired" control={control} defaultValue={false} label="Include Expired Policies" /> {/* Buttons */} <Button type="submit" variant="contained" color="primary">Search</Button> <Button type="button" variant="outlined" onClick={() => reset()} >Clear</Button> </form> ); } export default MyForm;
